// react-consumer/src/App.tsx
import React from "react";
import { createRoot } from 'react-dom/client';

import "remixicon/fonts/remixicon.css";
import "./index.scss";

// TODO: Lazy load/async load components from react to svelte
import Header from "home_remote/Header";
import Footer from "home_remote/Footer";
import SafeComponent from "./SafeComponent";

const App = () => (
  <div className="text-3xl mx-auto max-w-6xl">
	<SafeComponent>
		<Header />
	</SafeComponent>
		React Consumer
	<Footer />
  </div>
);


const root = createRoot(document.getElementById("app"));
root.render(<App />);

// pdp/src/App.svelte

<script>
  import CreateHeader from 'home_remote/CreateHeader';

  window.addEventListener("load", (event) => {
	let header = document.getElementById('header')
	let body = document.getElementsByTagName("body")[0]
	CreateHeader(header);
  });

</script>

<div class="text-3xl mx-auto max-w-6xl">
	<header id="header"></header>
	Svelte Consumer
</div>
